### ISSUE TITLE
Typo of "improvement" in resume

### ISSUE THREAD

**Issue by emsenn** [Keats/vincent.is#1]
Hey, I couldn't find the page within the source at a glance but wanted to let you know under your experiences, as a Freelancer, that you've got the last two letters of the word improvement switched around.

https://vincent.is/introducing-himself/

**Comment by Keats** [comment]
Thanks a lot!
The code is actually on gitlab (https://gitlab.com/Keats/vincent.is), I didn't realise I had this old one on Github
